language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    token:
      secure: cXy+o4/sTsq6wDu7BFQq+iY3UddCUWOeXXHXx0eKqCRRQFkLxIwis8ELTHmzjUTjDkwNBs7YHu7zGrawMNDQ2wxY67PEnlhkfwi/jhSOOMVc3P0z3U4gi+AiH7dXjaXP9582EA7zCA52eb0qdbduNSKvYo0bR7f8cYEDO4kpGd33vfvbBl6dTckwqBtBtm83YOGqIBaT35rwWx5ivN3CsGjo2c5nrkf12ceCR9/+9b/iFb9zs3eIaS8upw7RFW7xL61x+xsIlcQaIkbwBGmc1/o8Z+5f8Sxjej+owaxnaJK4B4RBMyJS4ScVIQfVac5OjCnpsE6buWGKwVPVGWxe5Q7ndzBgXdCD9zoMVFrRsgmMOsBjk2kvxdu7gFcUQw0HJwxY42+zXK3hfw1FkJ0nt/ekg5A/9HNHIHrQr+wCq8vZaKS+gkhrACfRT7cLZsfjC5XJsacvNn1tkLrXaL4BAOTUfNRigpykqRJ6F4jeREWbYbyuWuMrlkRAADFjL+EU9YAHWgaoSMm2K+nkJdKyfxZ21ifkU3w6p/9zKcUGATIiSzF/ZtNMdUxdSj8+yUL57q8NDrz1Fl3GbXg4SJdj+QDNqL0hTsCZb50Qjmji/F5XArnPWmejAs/4SxuDIZkK6qxxqy1DxecDANyi0nLs/h5tsDoP74irms19i5daP9w=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
