language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "michael-simons-github"
    token:
      secure: "Fon+RvXhbxzgExu6dEpXKnc+h5v81lqdkMc0PN1id42dfnXdQrAo/fPQH2Bem2+scsPivF8kxcgEATiTGVdDfoZvkXCmO8OpDXPlL/z+QK5W/azlIGg92WQosAW4FHemCB5mjMu8p0sU/Tr9QHy3cLDKAgbCjIgNbcH40duNARmIVav73mq/NBh7ZJzKLHkqf5hgJPNy2BeMDOuvun30pMX0TqC5sLLGXRGXImvpiGwe2bVxuSJCGDdOKIEXfhzqCmKy4B9ygg4tKAGn31itZisE34fFCyW2VvbrpCr0lASCJcSklRN1ajkbuuWN0V20ynLjH4EmnHxqcL8JWlJqv8nZQYwT3syqW4bkhuCzLcYlPWcfUsgHIGFkC4MzedGRjh4qGtbLtCEBGV8eckHXJU6BcT+55bkyGixhKUpoelOvi4vs5VrF8jPvWqEv72jMxTHE0x2OoZisZBVLTBbQ9Op6pymC70z+VbVjOGOizPSNi+PXX636mxEMJF6KlqJJ5PkPOIy4/Jy390Lc9QCBDVoHXwdk+H7zk7ogdyA6tssRVvKvpFxJzOrgEZptYVe/wnDnF9dZDa23k2DsrJpysqkACckdAsw+S5Tj/sKQOC4KMm529uNKTTRgli50tCC9zo1K6FbhoaLWoYz9u9NPVp5X8yDJF3iGbbduZXPk7D4="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
